version: ~> 1.0


import:
  - hapijs/ci-config-travis:node_js.yml@main
  - hapijs/ci-config-travis:os.yml@main

env:
  - TYPESCRIPT="latest"

install:
  - "npm install"
  - "npm install typescript@$TYPESCRIPT"

jobs:
  include:
  - os: "linux"
    node: "node"
    env: TYPESCRIPT="3.6"
  - os: "linux"
    node: "node"
    env: TYPESCRIPT="rc"
  - os: "linux"
    node: "node"
    env: TYPESCRIPT="next"
  allow_failures:
  - os: "linux"
    node: "node"
    env: TYPESCRIPT="next"
